### ISSUE TITLE
Suggestion: move tray icons directly to the left of main menu

### ISSUE THREAD

**Issue by coxackie** [zhangkaizhao/gnome-shell-extension-tray-icons#1]
I like very much the simplicity in your tray icons extension as compared to the other options out there. It also feels more stable - I did not have any issues up to now, as with the "competitors". Just a small suggestion: I find it personally preferable when tray icons are directly to the left of main menu. Right now they are put to the left of all existing extensions. Is this a change that you would consider? I realize you do not want to introduce settings and want to keep it clean, so it is up to you.

**Comment by coxackie** [comment]
Totally understood and respected. Thanks a lot for your work. As I have mentioned, up to now this rewrite has for some reason been more stable that TopIcons Plus or Redux - the latter two were sometimes turning off all extensions after wake-up from sleep mode; I have not noticed anything yet with Tray Icons.

 I will close this now - many thanks again.

**Comment by boistordu** [comment]
I think we need to revisit your position. 
Too much icons and it makes my default icons like button power etc to my second screen on the right because of a lacking of spaces for your extension. 
So it would be a good thing that in place of putting it somewhere or adding settings (since you don't want), that you would limit the number of icons to a specific number and add a submenu for the rest...
Do you want me to open a new issue for that or not?
