### ISSUE TITLE
Update for GNOME 3.34

### ISSUE THREAD

**Issue by coxackie** [zhangkaizhao/gnome-shell-extension-tray-icons#5]
Please see:
https://github.com/phocean/TopIcons-plus/pull/128/commits/454e3dc157ea1d91fffb6c0b3728ecdee6206860
Maybe you want to make the equivalent changes in your extension?

**Comment by zhangkaizhao** [comment]
Hi @coxackie ! Thanks for the notice. I already read it some days ago. And I have tested the removal of `actor` successfully in GNOME Shell 3.32 and 3.34. But it failed in GNOME Shell 3.28. Since the removal of `actor` is just a deprecation in GNOME Shell 3.34 and some OSes e.g. FreeBSD (ports) still stays at GNOME Shell 3.28, so I think it can be done later.

**Comment by coxackie** [comment]
ok understood - maybe I will just use it locally for the time being.
